### PR TITLE
feat(preflight): One-page inputs (Beta) for Template/Capture + macro script input support

### LINKED ISSUE #106: [FEATURE REQUEST] One pager to enter data
**Is your feature request related to a problem? Please describe.**
I have lots of forms that are multi-steps. Now I enter data on each form and go to the next.
When I make a mistake somewhere I need to interrupt a form and start it again. This is annoying and I waste a lot of time.

**Describe the solution you'd like**
You can provide an option to open all forms on one page.  I can then fill them all, review and check them and submit them at once.

### PR DESCRIPTION
**Pull request by chhoumann**
## Summary
- Introduces a Beta one-page input flow for Template & Capture choices, with per-choice override.
- Adds RequirementCollector + OnePageInputModal, recursive template scan, FIELD suggester, VDATE NL parsing/preview, capture target file-picker.
- Supports Macro preflight for user scripts exporting `quickadd.inputs` (non-executing) and adds `quickAddApi.requestInputs()` to collect multiple inputs at once from scripts.
- Skips the modal when all required inputs are prefilled; treats empty string as unresolved.
- Marks feature as Beta in settings and docs.

## Docs
- New page: Advanced → One-page Inputs.
- Settings: label and link to docs.

## Implementation notes
- Honors global toggle and per-choice override (always/never).
- Live filename preview scaffold in modal.
- References #106.

## Test plan
- Template choice with VALUE/VDATE/FIELD resolved via one-pager.
- Capture to folder/tag shows target file dropdown.
- Macro with user script declaring `quickadd.inputs` adds fields to the one-pager.
- Ensure modal does not open when variables are prefilled by an earlier step.

Closes #106

### CODE REVIEW

**Comment by tfiwm** [comment]
@chhoumann, is this feature disabled right now? because I get the following exception when I try run the API example mentioned in the section [Scripts: request inputs at runtime (API)](https://quickadd.obsidian.guide/docs/Advanced/onePageInputs#scripts-request-inputs-at-runtime-api). I also don't see following option to enable the feature: `Settings → QuickAdd → toggle “One-page input for choices”.`

```
plugin:quickadd:64 QuickAdd: (ERROR) Failed to run user script quickadd_onepage_input: quickAddApi.requestInputs is not a function TypeError: Failed to run user script quickadd_onepage_input: quickAddApi.requestInputs is not a function
    at entry (eval at SV (plugin:quickadd:1:1), <anonymous>:2:36)
    at yb.onExportIsFunction (plugin:quickadd:52:2040)
    at yb.userScriptDelegator (plugin:quickadd:52:1749)
    at yb.executeUserScript (plugin:quickadd:52:1239)
    at async yb.executeCommands (plugin:quickadd:52:607)
    at async yb.run (plugin:quickadd:52:411)
    at async WZ.onChooseMacroType (plugin:quickadd:77:2162)
    at async WZ.execute (plugin:quickadd:77:1817)
    at async b.onChooseItem (plugin:quickadd:77:1377)
```

**Comment by chhoumann** [comment]
Hey @tfiwm, I mistakenly announced it an update too early! The feature is introduced by 3ddf86c (feat(one-page-inputs)), which is after 2.1.0. It'll be released in the next update. Sorry for the confusion!
